ARDUINO_DIR            = /usr/share/arduino
TARGET                 = i2c_com
ARDUINO_LIBS           =
BOARD_TAG              = mega2560
MCU                    = atmega2560
F_CPU                  = 16000000
ARDUINO_PORT           = /dev/ttyACM0
AVRDUDE_ARD_BAUDRATE   = 115200

CPPFLAGS               = -fdiagnostics-color=always
LOCAL_CPP_SRCS         ?= $(wildcard *.cpp *.c)


include /usr/share/arduino/Arduino.mk
